
export const psits_roles = Object.freeze({
    ADMIN: "PSITS_SERV_ROLE_ADMINISTRATOR",
    DEVELOPER: "PSITS_SERV_ROLE_DEVELOPER",
    HEAD_FINANCE: "PSITS_SERV_HEAD_ROLE_FINANCE",
    FINANCE: "PSITS_SERV_ROLE_FINANCE",
    EXECUTIVE: "PSITS_SERV_ROLE_EXEC",
    STANDARD: "PSITS_SERV_ROLE_STANDARD",
    NO_ACCESS: "PSITS_SERV_ROLE_NONE",
    CAMPUS: "PSITS_SERV_ROLE_OTH_CAMPUS"
    
});
export const student_roles = Object.freeze({
    GENERAL: "PSITS_SERV_STUD_GENERAL",
    MEDIA: "PSITS_SERV_STUD_MEDIA",
    DEVELOPER: "PSITS_SERV_STUD_DEVELOPER",
    VOLUNTEER: "PSITS_SERV_STUD_VOLUNTEER",
    OFFICER: "PSITS_SERV_STUD_OFFICER"
    
})