name: PSITS Client

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Locate Client side directory
        working-directory: client-side
        run: |
          ls -la

      - name: Setup Node and Build Project
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: client-side/package-lock.json
      - run: npm install
        working-directory: client-side
      - run: npm run build
        working-directory: client-side

      - name: Deploy to Vercel
        working-directory: client-side
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Pulls Vercel token from GitHub secrets
        run: npx vercel --prod --token $VERCEL_TOKEN
